server:
  port: 8082

spring:
  application:
    name: delivery-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3307}/delivery_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_USER:smartcourier}
    password: ${MYSQL_PASSWORD:smartcourier}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:smartcourier}
    password: ${SPRING_RABBITMQ_PASSWORD:smartcourier}

clients:
  tracking:
    base-url: ${TRACKING_SERVICE_URL:http://localhost:8083}
