server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URI:https://github.com/Anmolsingh1222/SmartCourier-Delivery-Management-System-Sprint.git}
          search-paths: services/config-server/src/main/resources/config-repo
          default-label: main
          clone-on-start: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8762/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
